Repository upfluence/hypertable, pull requests merged in 2021-04, with the labels that each got.

#76 Pass allRowsSelected variable to contextual actions
  app/templates/components/hyper-table.hbs
Labels: reviewed/ready-to-merge

#77 Revert "Pass allRowsSelected variable to contextual actions"
  app/templates/components/hyper-table.hbs
Labels: reviewed/ready-to-merge

#78 templates/components: Add data-control-name attribute on row checkbox
  app/templates/components/hyper-table.hbs
  app/templates/components/hyper-table/views.hbs
Labels: enhancement, reviewed/ready-to-merge

#79 Update placeholder
  app/templates/components/hyper-table.hbs
Labels: reviewed/ready-to-merge

#80 Add filter data control name to filters menus
  addon/mixins/filters-renderer.js
  app/templates/components/hyper-table/column.hbs
  app/templates/components/hyper-table/facetting.hbs
  app/templates/components/hyper-table/filters-renderers/date.hbs
  app/templates/components/hyper-table/filters-renderers/money.hbs
  app/templates/components/hyper-table/filters-renderers/numeric.hbs
  app/templates/components/hyper-table/filters-renderers/text.hbs
Labels: enhancement, reviewed/needs-review
