Repository upfluence/hypertable, pull requests merged in 2022-02, with the labels that each got.

#127 Added: Ordering component for filter renderers
  addon/components/hyper-table-v2/filtering-renderers/common/ordering.hbs
  addon/components/hyper-table-v2/filtering-renderers/common/ordering.ts
  addon/components/hyper-table-v2/filtering-renderers/date.hbs
  addon/components/hyper-table-v2/filtering-renderers/date.ts
  addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
  addon/components/hyper-table-v2/filtering-renderers/numeric.ts
  addon/components/hyper-table-v2/filtering-renderers/text.hbs
  addon/components/hyper-table-v2/filtering-renderers/text.ts
  app/components/hyper-table-v2/filtering-renderers/common/ordering.js
  tests/integration/components/hyper-table-v2/filtering-renderers/common/ordering-test.ts
Labels: reviewed/ready-to-merge

#128 Added: Search Common component for filter renderers
  addon/components/hyper-table-v2/filtering-renderers/common/search.hbs
  addon/components/hyper-table-v2/filtering-renderers/common/search.ts
  addon/components/hyper-table-v2/filtering-renderers/text.hbs
  addon/components/hyper-table-v2/filtering-renderers/text.ts
  app/components/hyper-table-v2/filtering-renderers/common/search.js
  tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts
Labels: reviewed/ready-to-merge

#129 Hover state on rows
  addon/components/hyper-table-v2/cell.hbs
  addon/components/hyper-table-v2/cell.ts
  addon/components/hyper-table-v2/index.hbs
  addon/components/hyper-table-v2/index.ts
  tests/integration/components/hyper-table-v2-test.ts
  tests/integration/components/hyper-table-v2/cell-test.ts
Labels: reviewed/ready-to-merge

#130 Added Common Existence component filter renderer
  addon/components/hyper-table-v2/filtering-renderers/common/existence.hbs
  addon/components/hyper-table-v2/filtering-renderers/common/existence.ts
  addon/components/hyper-table-v2/filtering-renderers/common/ordering.hbs
  addon/components/hyper-table-v2/filtering-renderers/numeric.hbs
  addon/components/hyper-table-v2/filtering-renderers/numeric.ts
  addon/components/hyper-table-v2/filtering-renderers/text.hbs
  app/components/hyper-table-v2/filtering-renderers/common/existence.js
  tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
Labels: reviewed/ready-to-merge

#126 Add facetting support for the v2.
  addon/components/hyper-table-v2/column.ts
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
  addon/core/handler.ts
  addon/core/interfaces/manager.ts
  app/components/hyper-table-v2/filtering-renderers/common/facets-loader.js
  tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
  tests/unit/core/handler-test.ts
  translations/en-us.yaml
Labels: reviewed/needs-review

#131 Fix glitchy column swap
  addon/components/hyper-table-v2/index.hbs
  app/styles/columns.less
Labels: reviewed/ready-to-merge

#133 Integrate the addition of the Descriptors in the column definitions
  addon-test-support/table-manager.ts
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
  addon/core/interfaces/column.ts
  addon/core/rendering-resolver.ts
  tests/dummy/app/controllers/application.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
  tests/integration/components/hyper-table-v2/manage-columns-test.ts
  tests/unit/core/handler-test.ts
Labels: reviewed/ready-to-merge

#134 Remove: facetable_by assignation to null for testing...
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
Labels: reviewed/ready-to-merge

#136 Fix checkbox column disappear
  addon/components/hyper-table-v2/index.hbs
Labels: reviewed/ready-to-merge

#139 Fix display of to and from value in numeric filter
  addon/components/hyper-table-v2/filtering-renderers/numeric.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
Labels: reviewed/ready-to-merge

#140 Add apply-filter trigger event
  addon/components/hyper-table-v2/filtering-renderers/date.ts
  addon/core/handler.ts
  app/styles/inner-table.less
  tests/unit/core/handler-test.ts
Labels: reviewed/ready-to-merge

#143 filters/common/existence: allow passing down a filtering key
  addon/components/hyper-table-v2/filtering-renderers/common/existence.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
Labels: reviewed/ready-to-merge

#144 Added: Search now uses column definition attribute if it exists
  addon/components/hyper-table-v2/search.ts
Labels: reviewed/ready-to-merge

#145 Hide the first column from the Manage Fields component
  addon/components/hyper-table-v2/column.hbs
  addon/components/hyper-table-v2/column.ts
  addon/components/hyper-table-v2/manage-columns.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
  tests/integration/components/hyper-table-v2/manage-columns-test.ts
Labels: reviewed/ready-to-merge

#146 Fix hypertable performance issues
  addon/components/hyper-table-v2/index.ts
  addon/components/hyper-table-v2/manage-columns.hbs
  addon/components/hyper-table-v2/manage-columns.ts
  addon/core/handler.ts
Labels: reviewed/needs-review

#147 Remove flatpickrRef in date filter
  addon/components/hyper-table-v2/filtering-renderers/date.hbs
  addon/components/hyper-table-v2/filtering-renderers/date.ts
Labels: reviewed/ready-to-merge

#149 filtering-renderers/date: fix filter application
  addon/components/hyper-table-v2/filtering-renderers/date.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts
Labels: bug, reviewed/ready-to-merge

#150 Trigger event on Handler.resetRows
  addon/components/hyper-table-v2/search.ts
  addon/core/handler.ts
Labels: reviewed/ready-to-merge

#148 Display the number of selected rows in the header
  addon/components/hyper-table-v2/index.hbs
  addon/components/hyper-table-v2/index.ts
  addon/core/handler.ts
  tests/integration/components/hyper-table-v2-test.ts
Labels: reviewed/ready-to-merge
