Repository upfluence/hypertable, pull requests merged in 2025-01, with the labels that each got.

#220 Added locked state on list cell renderer
  addon/components/hyper-table/cell-renderers/list.hbs
  addon/components/hyper-table/cell-renderers/list.js
  app/styles/cells.less
  translations/en-us.yaml
Labels: reviewed/needs-review

#222 Add support for facets sorting (default by count)
  addon-test-support/table-manager.ts
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.hbs
  addon/components/hyper-table-v2/filtering-renderers/common/facets-loader.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
  tests/unit/core/handler-test.ts
Labels: reviewed/ready-to-merge

#221 Add sticky columns responsiveness fix
  app/styles/columns.less
  app/styles/hypertable.less
  app/styles/inner-table.less
Labels: reviewed/ready-to-merge

#223 Pnpm 8 to 10 & CI node version 20
  .github/workflows/ci.yml
  .nvmrc
  pnpm-lock.yaml
  tests/integration/components/hyper-table-v2-test.ts
  tests/integration/components/hyper-table-v2/cell-renderers/date-test.ts
  tests/integration/components/hyper-table-v2/cell-renderers/numeric-test.ts
  tests/integration/components/hyper-table-v2/cell-renderers/text-test.ts
  tests/integration/components/hyper-table-v2/cell-test.ts
  tests/integration/components/hyper-table-v2/column-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/column-actions-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/existence-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/ordering-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/search-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/numeric-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/text-test.ts
  tests/integration/components/hyper-table-v2/header-renderers/base-test.ts
  tests/integration/components/hyper-table-v2/manage-columns-test.ts
  tests/integration/components/hyper-table-v2/search-test.ts
  tests/integration/components/hyper-table-v2/selection-test.ts
  tests/integration/helpers/array-includes-test.ts
  tests/test-helper.ts
  tests/unit/core/handler-test.ts
  tests/unit/core/rendering-resolver-test.ts
Labels: reviewed/needs-review

#225 Scope the css var for # of columns to the table
  addon/components/hyper-table-v2/index.hbs
  addon/components/hyper-table-v2/index.ts
Labels: reviewed/ready-to-merge

#224 Fix deprecation: Remove this. & usage from hypertable
  addon/components/hyper-table/index.js
  addon/mixins/editable.js
Labels: reviewed/needs-review

#227 Add support for table-actions named block
  addon/components/hyper-table-v2/index.hbs
  addon/components/hyper-table-v2/manage-columns.hbs
  app/styles/header.less
  tests/integration/components/hyper-table-v2-test.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/common/facets-loader-test.ts
  translations/en-us.yaml
Labels: reviewed/needs-review

#228 Add timezone to moving filters on date filter renderers
  addon/components/hyper-table-v2/filtering-renderers/date.ts
  addon/components/hyper-table/filters-renderers/date.js
  addon/core/interfaces/column.ts
  tests/integration/components/hyper-table-v2/filtering-renderers/date-test.ts
Labels: reviewed/needs-work

#230 In ManageColumns, fix needed double-click when the user typed a keyword
  addon/components/hyper-table-v2/manage-columns.hbs
  addon/components/hyper-table-v2/manage-columns.ts
Labels: reviewed/ready-to-merge
